# Generated by Django 5.2.6 on 2025-09-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
