# Generated by Django 5.2.6 on 2025-09-21 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='classroom_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
