# Generated by Django 5.2.6 on 2025-10-19 07:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='lesson_point',
            new_name='credit_point',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='classroom',
        ),
        migrations.AddField(
            model_name='enrolment',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrolments', to='beacon.classroom'),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='graduated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='graduation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_semester_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='LessonClassroomAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_weeks', models.IntegerField(choices=[(2, '2 Weeks'), (3, '3 Weeks'), (4, '4 Weeks')])),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('schedule', models.CharField(blank=True, max_length=100, null=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='beacon.classroom')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='beacon.lesson')),
            ],
        ),
        migrations.AddField(
            model_name='enrolment',
            name='allocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='beacon.lessonclassroomallocation'),
        ),
        migrations.RenameModel(
            old_name='StudentReadingListProgress',
            new_name='StudentChecklistProgress',
        ),
        migrations.CreateModel(
            name='StudentChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('item_type', models.CharField(choices=[('READING', 'Reading'), ('ASSIGNMENT', 'Assignment'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='beacon.lesson')),
            ],
        ),
        migrations.AlterField(
            model_name='studentchecklistprogress',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beacon.studentchecklistitem'),
        ),
        migrations.DeleteModel(
            name='StudentReadingListItem',
        ),
    ]
