# Generated by Django 5.2.6 on 2025-10-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0002_rename_lesson_point_lesson_credit_point_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='font_size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=10),
        ),
    ]
