# Generated by Django 5.2.5 on 2025-09-11 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0002_studentprofile_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructorprofile',
            name='instructor_id',
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructorprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
