# Generated by Django 5.2.6 on 2025-09-21 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0002_alter_classroom_classroom_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='enrolled_students',
        ),
    ]
