# Generated by Django 5.2.5 on 2025-09-24 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0002_alter_lesson_lesson_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentReadingListProgress',
            new_name='StudentChecklistProgress',
        ),
        migrations.CreateModel(
            name='StudentChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('item_type', models.CharField(choices=[('READING', 'Reading'), ('ASSIGNMENT', 'Assignment'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='beacon.lesson')),
            ],
        ),
        migrations.AlterField(
            model_name='studentchecklistprogress',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beacon.studentchecklistitem'),
        ),
        migrations.DeleteModel(
            name='StudentReadingListItem',
        ),
    ]
