# Generated by Django 5.2.5 on 2025-09-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('INSTRUCTOR', 'Instructor')], default='STUDENT', max_length=50),
        ),
    ]
