# Generated by Django 5.2.6 on 2025-09-30 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0003_rename_studentreadinglistprogress_studentchecklistprogress_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='lesson_point',
            new_name='credit_point',
        ),
    ]
