# Generated by Django 5.2.6 on 2025-09-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0003_remove_lesson_enrolled_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='credit_point',
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_point',
            field=models.IntegerField(default=0),
        ),
    ]
