# Generated by Django 5.2.5 on 2025-09-03 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0003_alter_user_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
