# Generated by Django 5.2.6 on 2025-10-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0003_studentprofile_font_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='font_size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=10),
        ),
    ]
