# Generated by Django 5.2.6 on 2025-10-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0004_rename_lesson_point_lesson_credit_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentchecklistitem',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
