# Generated by Django 5.2.5 on 2025-10-19 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0004_instructorprofile_font_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='duration_weeks',
        ),
    ]
