# Generated by Django 5.2.6 on 2025-10-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0004_instructorprofile_font_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
