# Generated by Django 5.2.5 on 2025-09-17 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0005_lesson_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='credit_points',
            field=models.IntegerField(default=30, editable=False),
        ),
    ]
