# Generated by Django 5.2.6 on 2025-09-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0005_enrolment'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='unlocking_lessons', to='beacon.lesson'),
        ),
    ]
