# Generated by Django 5.2.6 on 2025-10-12 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0005_studentchecklistitem_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_semester_active',
            field=models.BooleanField(default=True),
        ),
    ]
