# Generated by Django 5.2.6 on 2025-10-19 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0005_alter_lesson_description'),
        ('beacon', '0005_remove_classroom_duration_weeks'),
    ]

    operations = [
    ]
