# Generated by Django 5.2.6 on 2025-10-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0005_remove_classroom_duration_weeks'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentchecklistitem',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
