# Generated by Django 5.2.6 on 2025-09-08 09:45

import django.contrib.auth.models
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0005_teacherprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeacherProfile',
            new_name='InstructorProfile',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('beacon.user',),
            managers=[
                ('instructor', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RenameField(
            model_name='instructorprofile',
            old_name='teacher_id',
            new_name='instructor_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STUDENT', 'Student'), ('INSTRUCTOR', 'Instructor')], max_length=50),
        ),
    ]
