# Generated by Django 5.2.6 on 2025-09-22 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0006_lesson_prerequisites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
