# Generated by Django 5.2.6 on 2025-10-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0006_user_is_semester_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
    ]
