# Generated by Django 5.2.6 on 2025-10-22 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0006_merge_20251020_0041'),
        ('beacon', '0006_studentchecklistitem_instructions'),
    ]

    operations = [
    ]
