# Generated by Django 5.2.5 on 2025-09-17 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0006_course_credit_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_id',
            field=models.CharField(editable=False, max_length=10),
        ),
    ]
