# Generated by Django 5.2.6 on 2025-10-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0007_instructorprofile_dark_mode_studentprofile_dark_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='schedule',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentchecklistitem',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
