# Generated by Django 5.2.5 on 2025-09-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0007_alter_lesson_lesson_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='assignment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
