# Generated by Django 5.2.5 on 2025-09-23 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0007_alter_lesson_lesson_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolment',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
