# Generated by Django 5.2.6 on 2025-10-19 06:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0007_instructorprofile_dark_mode_studentprofile_dark_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='classroom',
        ),
        migrations.AddField(
            model_name='enrolment',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrolments', to='beacon.classroom'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='graduated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='graduation_date',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='LessonClassroomAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_weeks', models.IntegerField(choices=[(2, '2 Weeks'), (3, '3 Weeks'), (4, '4 Weeks')])),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('schedule', models.CharField(blank=True, max_length=100, null=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='beacon.classroom')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='beacon.lesson')),
            ],
        ),
        migrations.AddField(
            model_name='enrolment',
            name='allocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='beacon.lessonclassroomallocation'),
        ),
    ]
