# Generated by Django 5.2.6 on 2025-09-18 04:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0007_alter_lesson_lesson_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='enrolled_students',
            field=models.ManyToManyField(blank=True, related_name='enrolled_lessons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='courses_enroling', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='TeacherProfile',
        ),
    ]
