# Generated by Django 5.2.6 on 2025-10-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0007_merge_20251022_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolment',
            name='course_enrolled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
