# Generated by Django 5.2.6 on 2025-09-19 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0008_lesson_assignment'),
        ('beacon', '0008_lesson_enrolled_students_alter_course_students_and_more'),
    ]

    operations = [
    ]
