# Generated by Django 5.2.6 on 2025-09-24 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0008_enrolment_completed_lessontask'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('estimated_time', models.CharField(max_length=50)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='beacon.lesson')),
            ],
        ),
    ]
