# Generated by Django 5.2.6 on 2025-09-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0009_alter_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='title',
            field=models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Ms', 'Ms'), ('Mrs', 'Mrs'), ('Dr', 'Dr')], max_length=10, null=True),
        ),
    ]
