# Generated by Django 5.2.5 on 2025-09-20 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0009_classroom_lesson_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20),
        ),
    ]
