# Generated by Django 5.2.6 on 2025-09-19 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0009_merge_20250919_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom_id', models.CharField(max_length=20)),
                ('duration_weeks', models.PositiveIntegerField(choices=[(2, '2 weeks'), (3, '3 weeks'), (4, '4 weeks')])),
                ('supervisor', models.CharField(max_length=100)),
                ('building', models.CharField(blank=True, max_length=100, null=True)),
                ('room', models.CharField(blank=True, max_length=50, null=True)),
                ('online_link', models.URLField(blank=True, null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='beacon.course')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='beacon.classroom'),
        ),
    ]
