# Generated by Django 5.2.6 on 2025-09-18 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0010_studentprofile_first_name_studentprofile_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='student_id',
        ),
    ]
